### ISSUE TITLE
1.6.0 breaks webpack build

### ISSUE THREAD

**Issue by hyperivo** [yiminghe/css-animation#20]
I'm experiencing the following error with 1.6.0 while doing a production build with webpack, reverting to 1.5.0 fixes the problem.
```
=============
Failed to compile.

./node_modules/antd/es/_util/wave.js
Cannot find module: 'css-animation/es/Event'. Make sure this package is installed.

You can install this package by running: npm install css-animation/es/Event.
```

To mitigate the issue I added the following to my package.json
```
"resolutions": {
    "css-animation": "1.5.0"
  }
```

**Comment by vidhu** [comment]
To be clear, 1.6.0 is breaking [`antd`](https://github.com/ant-design/ant-design/) 

Looking at the diff here https://diff.intrinsic.com/css-animation/1.5.0/1.6.0
the changes introduced are breaking changes in 1.6.0 is breaking changes. Therefore, according to [semver](https://semver.org/) the new version should be 2.X.X. i.e major version should be bumped not minor or patch...

I'm pretty sure a lot of other packages that depend on this are breaking now

**Comment by michshat** [comment]
Also getting the error related to 1.6.0 in azure:
`Module not found: Error: Can't resolve 'css-animation/es/Event' in 'D:\a\1\s\ui\node_modules\antd\es\_util'`

**Comment by Nilegfx** [comment]
@vidhu not sure whom to blame here, consumers or publishers. 

Of course publishers has to respect semver, however, I think consumers also should also take some preventive actions like not using the internals of a library or if they have to, at least stick with a specific version.

**Comment by VinayakRugvedi** [comment]
Well, I am using "rc-collapse" which is in turn using this package
With this package's new release, its breaking!
Module not found: Error: Can't resolve 'css-animation'

**Comment by yyfearth** [comment]
The 1.6.0 changed file path, so it should be 2.0.0 in this case for semver, otherwise npm will use the 1.6.0 for `^1.x.x` and break the packages.

**Comment by fjc0k** [comment]
https://unpkg.com/browse/css-animation@1.6.0/package.json

![image](https://user-images.githubusercontent.com/13151189/62005532-33c7f100-b167-11e9-96dc-41a020c04af0.png)

no `main` ?????

**Comment by ndiaz-candido** [comment]
Same here
<img width="1127" alt="Screen Shot 2019-07-28 at 5 59 01 AM" src="https://user-images.githubusercontent.com/25233189/62005716-d5febf00-b0fc-11e9-8335-edc1887a186d.png">

**Comment by davidtran** [comment]
Antd is a huge library, they should fixed the version of their dependencies. Now we have to guess the next dependency update will cause this similar error.

**Comment by gorlikariel** [comment]
explicitly install 1.5.0 to patch antd
`"css-animation": "1.5.0" (in package.json)`

**Comment by iamsail** [comment]
what a big things

**Comment by yiminghe** [comment]
sorry, 1.6.1(1.5.0) published

**Comment by chachaxw** [comment]
This is a really bad update.😭
